---
- name: Ensure firewalld is stopped and disabled
  service: name=firewalld state=stopped enabled=no
  when: ansible_distribution_major_version == "7"
  failed_when: false

- name:  Install iptables packages
  yum:
    name: "{{ iptables_pkgs }}"
    state: present

